name: Rust Binary Release and Homebrew Formula Update

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # 安装 Rust
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-apple-darwin
            aarch64-apple-darwin

      - name: Build Release Binary x86_64
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build Release Binary aarch64
        run: cargo build --release --target aarch64-apple-darwin

      - name: Tar Release Binary
        run: |
          tar czvf imggen-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz -C target/x86_64-apple-darwin/release imggen
          tar czvf imggen-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz -C target/aarch64-apple-darwin/release imggen

      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 imggen-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz | awk '{print $1}')
          echo "$SHA256" > imggen-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz.sha256
          SHA256_AARCH64=$(shasum -a 256 imggen-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz | awk '{print $1}')
          echo "$SHA256_AARCH64" > imggen-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz.sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            imggen-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
            imggen-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz
            imggen-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz.sha256
            imggen-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz.sha256
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update Homebrew Formula
      #   run: |
      #     cat << EOF > Formula/imggen.rb
      #     class imggen < Formula
      #       desc "imggen is a test image generation tool that can generate images"
      #       homepage "https://github.com/ChurchTao/imggen"
      #       url "https://github.com/ChurchTao/imggen/releases/download/${{ github.ref_name }}/imggen-${{ github.ref_name }}.tar.gz"
      #       sha256 "${{ steps.sha256.outputs.sha256 }}"

      #       def install
      #         bin.install "imggen" => "imggen"
      #       end

      #       test do
      #         system "#{bin}/imggen", "-V"
      #       end
      #     end
      #     EOF

      # - name: Push Homebrew Formula
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #   with:
      #     source-directory: "Formula"
      #     destination-github-username: "your_github_username"
      #     destination-repository-name: "homebrew-yourprogram"
      #     user-email: "your-email@example.com"
      #     commit-message: "Bump imggen to ${{ github.ref_name }}"
